name: Release the package

on:
  release:

jobs:
  build:
    name: Build the package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Cache pip
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
        with:
          path: .cache/pip
          key: pip-cache-${{ runner.os }}-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            pip-cache-${{ runner.os }}-

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.12"

      - name: Prepare building
        run: pip install build
      - name: Build
        run: python -m build

      - name: Upload dists
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    needs:
      - build
    environment:
      name: pypi
      url: https://pypi.org/p/intelmq-checkmk-extensions
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: release-dists
          path: dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
